services:
  - type: web
    name: student-management-system
    env: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/student-management-system-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_URL
        fromEnvVar: DB_URL
      - key: DB_USER
        fromEnvVar: DB_USER
      - key: DB_PASS
        fromEnvVar: DB_PASS
