services:
  - type: web
    name: student-management-system
    runtime: docker
    plan: free
    envVars:
      - key: DB_URL
        fromEnvVar: DB_URL
      - key: DB_USERNAME
        fromEnvVar: DB_USERNAME
      - key: DB_PASSWORD
        fromEnvVar: DB_PASSWORD
    autoDeploy: true
